- name: Fake LDAP for server
  hosts: lustre-storage[0]
  gather_facts: false
  become: true
  tasks:
    - name: create project owner users/groups
      include_tasks: create-users.yml
      vars:
        users: "{{ projects[item].users }}"
      loop: "{{ projects.keys() }}"

    - name: create demo user user/groups
      include_tasks: create-users.yml
      vars:
        users: "{{ hostvars['lustre-client1']['users'] }}"

- name: Setup client users
  hosts: lustre_client:!admin_client
  gather_facts: false
  become: true
  tasks:
    - name: create project owner users/groups
      include_tasks: create-users.yml
      vars:
        users: "{{ projects[item].users }}"
      loop: "{{ projects.keys() }}"

    - name: create demo user user/groups
      include_tasks: create-users.yml
      
    